language: go

install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

go:
- master
- tip

script:
- go test -v ./...
- go test -v -covermode=count -coverprofile=coverage.out
- $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
